# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  #welcome: circleci/welcome-orb@0.4.1
  matlab: mathworks/matlab@0.4.0
  
# Orchestrate or schedule a set of jobs
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      #- run: sudo add-apt-repository ppa:mc3man/gstffmpeg-keep
      #- run: sudo apt-get update 
      #- run: sudo apt-get install gstreamer0.10-ffmpeg
      #- run: sudo apt-get install gstreamer0.10-tools
      #- run: sudo apt-get install gstreamer0.10-plugins-good
      - matlab/install
      - matlab/run-command:
          command: makehorseproj

